const PROJECTS = [
  { title: "детская художественная школа", city: "альметьевск", year: "2022", image: "project-01.jpg" },
  { title: "детская художественная школа", city: "альметьевск", year: "2022", image: "project-02.jpg" },
  { title: "детская художественная школа", city: "альметьевск", year: "2022", image: "project-03.jpg" },
  { title: "детская художественная школа", city: "альметьевск", year: "2022", image: "project-04.jpg" },
  { title: "детская художественная школа", city: "альметьевск", year: "2022", image: "project-02.jpg" },
  { title: "детская художественная школа", city: "альметьевск", year: "2022", image: "project-03.jpg" },
  { title: "детская художественная школа", city: "альметьевск", year: "2022", image: "project-04.jpg" },
  { title: "детская художественная школа", city: "альметьевск", year: "2022", image: "project-01.jpg" },
  { title: "Реновация физико-математического лицея", city: "альметьевск", year: "2016", image: "project-05.jpg" },
  { title: "Реновация физико-математического лицея", city: "альметьевск", year: "2016", image: "project-06.jpg" },
  { title: "Реновация физико-математического лицея", city: "альметьевск", year: "2016", image: "project-07.jpg" },
  { title: "Реновация физико-математического лицея", city: "альметьевск", year: "2016", image: "project-08.jpg" },
  { title: "Реновация культурного центра Космос в Лениногорске", city: "лениногорск", year: "2016", image: "project-04.jpg" },
  { title: "Клубный жилой дом", city: "альметьевск", year: "2016", image: "project-02.jpg" },
  { title: "Концепция офисно-производственного кластера", city: "альметьевск", year: "2016", image: "project-03.jpg" },
  { title: "ПЕРЕЦ", city: "альметьевск", year: "2016", image: "project-08.jpg" },
];
